# 使用 OpenJDK 基础镜像
FROM eclipse-temurin:21-jdk

# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 安装 FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制预先构建好的 jar 文件
COPY target/speaking-0.0.1-SNAPSHOT.jar app.jar

# 暴露端口
EXPOSE 2580

# 启动命令
ENTRYPOINT ["java", "-jar", "app.jar"]