FROM amazoncorretto:21

# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 设置工作目录
WORKDIR /app

# 复制jar包
COPY target/speaking-0.0.1-SNAPSHOT.jar app.jar

# 暴露端口
EXPOSE 2580

# 启动命令
ENTRYPOINT ["java", "-jar", "app.jar"]