server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/speaking_db
spring.datasource.username=alsay_mac
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# DeepSeek 配置
deepseek.api.key=sk-282c672589e245cf99c2d8316b0071d1
deepseek.api.url=https://api.deepseek.com/chat/completions
deepseek.api.model=deepseek-chat
